name: Deploy MERN App to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Backend & Frontend to Google Cloud Run
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REPO_NAME: ${{ secrets.GCP_REPO_NAME }}
      LOCATION: ${{ secrets.GCP_LOCATION }}
      OCR_ID: ${{ secrets.GCP_OCR_ID }}
      PROCESSOR_ID: ${{ secrets.GCP_PROCESSOR_ID}}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY}}
      INVOICE_ID: ${{ secrets.GCP_INVOICE_ID}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker Authentication for Artifact Registry
        # Authenticates Docker to push/pull images from Google Artifact Registry.
        run: gcloud auth configure-docker asia-south2-docker.pkg.dev

      # Ensure Docker Buildx is properly set up.
      # This action is crucial for `docker buildx build` to function correctly
      # and avoids potential "requires 1 argument" errors related to buildx setup.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # --- Backend Deployment ---
      - name: Verify Backend Directory Exists
        # Check if the './backend' directory exists before attempting to build.
        # This helps catch issues if the directory path is incorrect or missing.
        run: |
          if [ ! -d "./backend" ]; then
            echo "Error: Backend directory './backend' not found!"
            exit 1
          fi
          echo "Backend directory './backend' found. Proceeding with build."

      - name: Build and Push Backend Docker Image
        # Builds the Docker image for the backend and pushes it to Google Artifact Registry.
        # The --tag flag names the image, and --push uploads it.
        run: |
          docker buildx build ./backend \
            --tag asia-south2-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/backend:latest \
            --push

      - name: Deploy Backend to Cloud Run
        # Deploys the backend Docker image to Google Cloud Run.
        # Sets various environment variables for the Cloud Run service.
        run: |
          gcloud run deploy backend-service \
            --image asia-south2-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/backend:latest \
            --region asia-south2 \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars="GCP_PROJECT_ID=$PROJECT_ID,GCP_LOCATION=$LOCATION,GCP_PROCESSOR_ID=$PROCESSOR_ID,GCP_OCR_ID=$OCR_ID,GCP_INVOICE_ID=$INVOICE_ID,GEMINI_API_KEY=$GEMINI_API_KEY"

      # --- Frontend Deployment ---
      - name: Verify Frontend Directory Exists
        # Check if the './frontend' directory exists before attempting to build.
        run: |
          if [ ! -d "./frontend" ]; then
            echo "Error: Frontend directory './frontend' not found!"
            exit 1
          fi
          echo "Frontend directory './frontend' found. Proceeding with build."

      - name: Build and Push Frontend Docker Image
        # Builds the Docker image for the frontend and pushes it to Google Artifact Registry.
        run: |
          docker buildx build ./frontend \
            --tag asia-south2-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/frontend:latest \
            --push

      - name: Deploy Frontend to Cloud Run
        # Deploys the frontend Docker image to Google Cloud Run.
        run: |
          gcloud run deploy doc-aid \
            --image asia-south2-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/frontend:latest \
            --region asia-south2 \
            --platform managed \
            --allow-unauthenticated
